### ISSUE TITLE
How to select STL_capture as default audio input device in rpi3 stretch

### ISSUE THREAD

**Issue by titusece** [STMicroelectronics-CentralLabs/BlueVoice-for-Linux#3]
Hello,

I am using raspberry pi3 board and stretch raspian OS and would like to use this device as default audio input device (STL_capture)

Started the STL_capture:
`sudo python3 main.py stl_capture 8000
`
Used the below commands to record the audio from sensortile board.
```
arecord -D hw:1,1 -f S16_LE test.wav
arecord -D STL_capture -f S16_LE -r 16000 -c 1 test.wav

```
but I wanted to run single command like this "arecord test.wav" because I have to use this audio capture for dialogflow audio stream to detect the speech intents.

[https://github.com/dialogflow/dialogflow-python-client-v2/blob/master/samples/detect_intent_stream.py](url)

The below example uses 'speech_recognition' for capturing the audio stream but dialogflow uses other recording method which I am trying now, I would like to change the STL_capture device as default input device.
With my USB mic, I could capture the audio and detect speech intent by dialogflow, and I need to try to do the same with ST_capture audio device (BLE audio)
[https://github.com/STMicroelectronics-CentralLabs/BlueVoice-for-Linux/tree/master/Speech2Text_google](url)

Tried to set the following lines into ~/.asoundrc file, no luck.
```
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,1"
     format S16_LE
   }
}   
pcm.STL_capture {
 type plug
 slave.pcm "ploop"
 }
 
 pcm.ploop {
  type hw
  card Loopback
  device 1
  subdevice 0
  format S16_LE
  rate 16000
  channels 1
}

```
Can you please help me to solve this issue ?

**Comment by titusece** [comment]
Any help please ?

**Comment by NeeoKevin** [comment]
I'm not sure if I understood you right.
First you need to run this command to connect your Bluetooth device with your raspberry and to create the microphone peripheral.
`sudo python3 main.py stl_capture 16000`
If you wanna change the default capture and playback source it does not work if you modify "~/.asoundrc" file.
I had the similar issue.
I analyzed the main.py script and there you will see as soon you run the command above it will copy the settings from the file "asoundrc_template_16KHz" to the "~/.asoundrc" file.
Same case if you record with 8kHz but there it will copy the settings from the "asoundrc_template_8KHz" file.
So if you wanna have special settings while you running the main.py you need to add your settings to the files "asoundrc_template_8KHz" or/and "asoundrc_template_16KHz" before, which you find at BlueVoice-for-Linux/BVLINK_rbpi3/

**Comment by titusece** [comment]
Thats right.
Thanks for the insights.
