### ISSUE TITLE
frequency 16000 is not working properly with raspberry pi3 board

### ISSUE THREAD

**Issue by titusece** [STMicroelectronics-CentralLabs/BlueVoice-for-Linux#4]
Hello,
Running ALLMEMs example on SensorTile STM32 board.

To create a 16KHz microphone peripheral named STL_capture.
> sudo python3 main.py stl_capture 16000

Capture the audio:
> arecord -D STL_capture -f S16_LE -r 16000 -c 1 record1.wav

Getting noisy and different voice while running the record1.wav file.

With 8000 audio frequency, its works perfectly  but 16000 rate.
sudo python3 main.py stl_capture 8000
arecord -D STL_capture -f S16_LE -r 8000 -c 1 record1.wav

Can you please help to solve this issue ?

**Comment by phanindras** [comment]
Hi,
Check whether the device you are using for capturing supports 16KHz.

**Comment by titusece** [comment]
Yes, thats right, seems STM32 board was configured to send 8KHz sampling audio.
I found the following code in STM32 audio BLE code, changed FR_8000 to FR_16000 and BV_AUDIO_SAMPLING_FREQUENCY for 16KHz, but its not working properly, noisy and can't be used for voice recognition, unlike FR_8000.

//  BLUEVOICE_Config.sampling_frequency = FR_8000;
  BLUEVOICE_Config.sampling_frequency = FR_16000;
  BLUEVOICE_Config.channel_in = 1;
  BLUEVOICE_Config.channel_tot = 1;

  bvStat = BluevoiceADPCM_SetConfig(&BLUEVOICE_Config);
  if (bvStat != BV_ADPCM_SUCCESS) {
    goto fail;
  }

//#define BV_AUDIO_SAMPLING_FREQUENCY     8000
#define BV_AUDIO_SAMPLING_FREQUENCY     16000
#define BV_AUDIO_VOLUME_VALUE           64
#define PCM_IN_SAMPLES_PER_MS           (((uint16_t)BV_AUDIO_SAMPLING_FREQUENCY)/1000)
#define AUDIO_IN_MS                     (1)       /*!< Number of ms of Audio given as input to the BlueVoice library.*/ 
#define BV_PCM_AUDIO_IN_SAMPLES         (PCM_IN_SAMPLES_PER_MS * AUDIO_IN_MS)

Can you please help me to solve this issue ?

**Comment by faenzafernando** [comment]
Hi titusece, 

did you try also this configuration step for stm32 application?


```
aci_l2cap_connection_parameter_update_request(handle,
                                              8 /* interval_min*/,
                                              8 /* interval_max */,
                                              0   /* slave_latency */,
                                              400 /*timeout_multiplier*/);
```

**Comment by titusece** [comment]
Hi,
Thanks for the reply.
The prebuilt binary itself gives noisy audio, I stick with 8KHz for now.
I have another end to support 8KHz.
