### ISSUE TITLE
issue launching application

### ISSUE THREAD

**Issue by zhinii** [STMicroelectronics-CentralLabs/BlueVoice-for-Linux#5]
when running:
 sudo python3 main.py stl_capture 16000

ill get an:
'OSError: PortAudio library not found' error

this is on a beaglbone black.

**Comment by faenzafernando** [comment]
Hi zhinii,

did you try to install libportaudio2 and libasound-dev ?

Actually this project is deprecated and i really suggest you to get our BlueST SDK that supports adpcm and more over features.

https://github.com/STMicroelectronics-CentralLabs/BlueSTSDK_Python

**Comment by zhinii** [comment]
was missing the libportaudio2 and now itll connect.

but when recording itll throw a new error.

debian@beaglebone:/var/lib/cloud9/final/BlueVoice-for-Linux/BVLINK_rbpi3$  arecord -D STL_capture -f S16_LE -r 16000 -c 1 record1.wav
Recording WAVE 'record1.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
record1.wav: Permission denied

**Comment by zhinii** [comment]
about issue resolve forgot su
